services:
  user-service:
    env_file:
      - .env
    build: .
    ports:
      - "${PORT:-3001}:3001"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=userdb
      - DB_USER=user
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      - mariadb
      - redis
    networks:
      - default
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-userdb}
      - MYSQL_USER=${MYSQL_USER:-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 30s
      retries: 50

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
      - db-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50

networks:
  default:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/db-data
      o: bind
