# infrastructure/docker-compose.yml
version: "3.9"

services:

  mariadb:
    image: mariadb:11.4
    container_name: vpndoc_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-strict-mode=ON
      --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO

  redis:
    image: redis:7.2-alpine
    container_name: vpndoc_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass redispass123
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru

  redpanda:
    image: redpandadata/redpanda:v23.3.11
    container_name: vpndoc_redpanda
    restart: unless-stopped
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "9092:9092"
      - "8082:8082"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: vpndoc_keycloak
    restart: unless-stopped
    command: start-dev          # dev mode ໃຊ້ H2 in-memory
    environment:
      KEYCLOAK_ADMIN:          admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HTTP_PORT:            8080
      KC_HOSTNAME_STRICT:      "false"
      KC_LOG_LEVEL:            INFO
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  mariadb_data:
  redpanda_data:
  keycloak_data: